name: escouniv
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3
 # firebase_auth: ^0.6.2+1
  google_sign_in:
  shared_preferences: ^0.4.0
  flutter_facebook_login: ^2.0.1
  async_loader: ^0.1.2
#  cupertino_icons: ^0.1.2
  flutter_html_textview: ^0.2.6
  image_picker: ^0.6.0+17
  grouped_buttons: ^1.0.4
  modal_progress_hud: ^0.1.3
  file_picker: ^1.3.8
  flutter_image_compress: ^0.6.3
  connectivity: ^0.4.4

  datetime_picker_formfield: ^0.1.1
  webview_flutter: ^0.3.10+4
  back_button_interceptor: ^4.0.7
  flutter_webrtc : ^0.1.7
  firebase_messaging: ^5.1.5
 # firebase_auth: 0.5.4
  overlay_support: ^1.0.0
  flutter_section_table_view: ^1.0.5


  #firebase_core: ^0.4.0


#      firebase_auth: ^0.11.1+6
#      cloud_firestore: ^0.12.5
#
#      firebase_messaging: ^5.0.2

#firebase_messaging: ^5.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

test: 0.12.30+3
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - Assets/Images/bg.png
    - Assets/Images/logo.png
    - Assets/Images/logo-escouniv.png
    - Assets/Images/DefaultUser.png
    - Assets/Images/Menuhome.png
    - Assets/Images/MenucomAnnouncement.png
    - Assets/Images/MenuempAnnouncement.png
    - Assets/Images/Person.png
    - Assets/Images/Menumessage.png
    - Assets/Images/Menuescouniv.png
    - Assets/Images/redlogout.png
    - Assets/Images/MenuappointmentHistory.png
    - Assets/Images/MenuDocumentReview.png
    - Assets/Images/MenuappointmentHistory.png
    - Assets/Images/MenuBriefing.png
    - Assets/Images/MenuAvailability.png
    - Assets/Images/MenuEscobriefings.png
    - Assets/Images/DrawerBg.png
    - Assets/Images/Istoric.png
    - Assets/Images/Firme.png
    - Assets/Images/Chestionare.png
    - Assets/Images/RedactiveCV.png
    - Assets/Images/Compressarrow.png
    - Assets/Images/Consiliere.png
    - Assets/Images/Vector.png
    - Assets/Images/calender_black.png
    - Assets/Images/Watch_black.png
    - Assets/Images/thumbnail_image.png
    - Assets/Images/infoVector.png
    - Assets/Images/reddot.png
    - Assets/Images/EditMode.png
    - Assets/Images/EmailVector.png
    - Assets/Images/Vectorpassword.png
    - Assets/Images/Vectorgoogle.png
    - Assets/Images/Vectorfacebook.png
    - Assets/Images/MenuMentor.png
    - Assets/Images/userimage.png
    - Assets/Images/MenuPC.png
    - Assets/Images/expandarrow.png
    - Assets/Images/DefaultSuccess.png
    - Assets/Images/Success.png
    - Assets/Images/CareerplanEdit.png
  fonts:
    - family: Demi
      fonts:
        - asset: Assets/fonts/AvenirNextLTPro-Demi.otf
    - family : regular
      fonts:
        - asset: Assets/fonts/AvenirNextLTPro-Regular.otf
    - family : italic
      fonts:
          - asset: Assets/fonts/AvenirNextLTPro-It.otf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
